# Controls when the workflow will run
on:
  push:
    tags:
        - "*.*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: build executable
        run: |
          stack build
          find .stack-work/install -name oschark -exec mv {} . \;
      - name: save executable as artifact
        uses: actions/upload-artifact@v2
        with:
          name: oschark_${{matrix.os}}
          path: oschark

  release:
    runs-on: ubuntu-latest
    steps:
      - name: retrive artifacts
        uses: actions/download-artifact@v2
      - name: do Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
              oschark_*
              LICENSE

