# Controls when the workflow will run
on:
  push:
    tags:
        - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: build executable
        run: |
          stack build
          find .stack-work/install -name oschark -exec mv {} . \;
      - name: do Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
              oschark
              LICENSE
        